apiVersion: v1
kind: Service
metadata:
  name: vet-backend-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  selector:
    app: vet-backend
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vet-backend
  labels:
    app: vet-backend
spec:
  selector:
    matchLabels:
      app: vet-backend
  template:
    metadata:
      labels:
        app: vet-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: vet-backend
        image: headitapps.azurecr.io/hgh9/vetty-backend:latest
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 150m
            memory: "512Mi"
          limits:
            cpu: 300m
            memory: "1024Mi"
        # env:
        # - name: NODE_ENV
        #   value: "production"
        
        # imagePullPolicy: Always
      # serviceAccountName: default