#NAME
name: Push images to Dockerhub and pull to the ubuntu server
#EVENT
on:
  push:
    branches:
      - "main"

#JOBS
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./vet_nest
          file: ./vet_nest/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vetty-backend-backend:latest
      - name: docker-compose up -d 
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            sudo docker-compose --project-directory ./app pull &&
            sudo docker-compose --project-directory ./app --env-file ./app/.env up -d --remove-orphans &&
            sudo docker image prune

          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}   
          password: ${{ secrets.SSH_PASSWORD}}   
